### PR TITLE
fix bluetooth disconnect message display

### PR DESCRIPTION
**Pull request by racerx**

### CODE REVIEW

**Comment by ishotjr** [comment]
@racerx I'm not sure how the underlying event service works (let along the emulated version) but on the real hardware, it can sometimes take a moment before it seems to "realize". :bowtie: :grey_question: :watch:

**Comment by racerx** [comment]
​@ishotjr yes on the emulator there is an error that shows up on the
console that I think is an error with qemu. it works but is not the same
amount of time perhaps by design.
​
Unhandled exception in thread started by <bound method Thread.__bootstrap
of <Thread(Thread-1, stopped daemon 140647341397760)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 823, in __bootstrap_inner

**Comment by ishotjr** [comment]
@racerx Was this merge automatic?  For some reason the Travis build failed:

``` bash
Using worker: worker-linux-027f0490-2.bb.travis-ci.org:travis-linux-5
system_info
Build system information
Build language: pebblec
Build image provisioning date and time
Wed Feb  4 18:22:50 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:    12.04
Codename:   precise
Linux Version
2.6.32-042stab090.5
Cookbooks Version
23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"
0.11s$ git clone --depth=50 git://github.com/ishotjr/pw-dos.git ishotjr/pw-dos
Cloning into 'ishotjr/pw-dos'...
remote: Counting objects: 70, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 70 (delta 29), reused 67 (delta 29), pack-reused 0
Receiving objects: 100% (70/70), 37.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (29/29), done.
Checking connectivity... done.
$ cd ishotjr/pw-dos
3.20s$ git fetch origin +refs/pull/9/merge:
fatal: Couldn't find remote ref refs/pull/9/merge
The command "eval git fetch origin +refs/pull/9/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/9/merge
The command "eval git fetch origin +refs/pull/9/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/9/merge
The command "eval git fetch origin +refs/pull/9/merge:" failed 3 times.
The command "git fetch origin +refs/pull/9/merge:" failed and exited with 128 during .
Your build has been stopped.
```

**Comment by racerx** [comment]
It built ok on both my Linux box and mpb. Looks like this thread is about it here: https://github.com/travis-ci/travis-ci/issues/617

**Pull request merged**
